### ISSUE TITLE
No external id saved for certain jobs submitted

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/ridgeback#15]
No external id submitted or saved in Ridgeback for some hard-to-determine-why jobs running on LSF

**Comment by stevekm** [comment]
This might benefit from just using a wrapper-script around the commands submitted in your `bsub` and writing out the value of `LSB_JOBID` to a file in the job's working directory.

This would be advantageous because it would not rely on the stdout messages from the scheduler, which can become unpredictable when the HPC is under load or other stress. Instead you would get the job ID directly from inside the running job, which is likely more reliable since a valid job ID must exist if the job is running and there would be fewer potential things blocking its retrieval from a file vs. retrieval from the `bsub` command stdout

LSF job environment variables reference: https://www.ibm.com/support/knowledgecenter/SSWRJV_10.1.0/lsf_config_ref/lsf_envars_ref.html

**Comment by stevekm** [comment]
different cases have been encountered with this

- a job is created in Ridgeback and given the CREATED status, but never actually gets submitted to LSF and so no external ID is recorded

- a job is created in Ridgeback and set to CREATED state, then is successfully submitted to LSF but no external ID is recorded
